# syntax=docker/dockerfile:1

FROM golang:1.18-alpine

RUN apk add --no-cache gcc libc-dev

WORKDIR /app

COPY ./go.mod ./
COPY ./go.sum ./
RUN go mod download

COPY ./app/*.go ./

RUN mkdir db
COPY ./db/items.db ./db/

RUN go build -o /docker-gs-ping

# STEP4-4では以下は変更しない
CMD [ "/docker-gs-ping" ]
#CMD ["tail", "-f", "/dev/null"]
